/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasacionRouteImport } from './routes/tasacion'
import { Route as RentaRouteImport } from './routes/renta'
import { Route as PublicaRouteImport } from './routes/publica'
import { Route as PropiedadesRouteImport } from './routes/propiedades'
import { Route as CompraRouteImport } from './routes/compra'
import { Route as AcercaRouteImport } from './routes/acerca'
import { Route as VendedorRouteImport } from './routes/_vendedor'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendedoresSignupRouteImport } from './routes/vendedores.signup'
import { Route as VendedoresLoginRouteImport } from './routes/vendedores.login'
import { Route as PropiedadesIdRouteImport } from './routes/propiedades.$id'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as VendedorVendedoresDashboardRouteImport } from './routes/_vendedor.vendedores.dashboard'
import { Route as VendedorVendedoresPropiedadesNuevaRouteImport } from './routes/_vendedor.vendedores.propiedades.nueva'
import { Route as VendedorVendedoresPropiedadesIdEditarRouteImport } from './routes/_vendedor.vendedores.propiedades.$id.editar'

const TasacionRoute = TasacionRouteImport.update({
  id: '/tasacion',
  path: '/tasacion',
  getParentRoute: () => rootRouteImport,
} as any)
const RentaRoute = RentaRouteImport.update({
  id: '/renta',
  path: '/renta',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicaRoute = PublicaRouteImport.update({
  id: '/publica',
  path: '/publica',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesRoute = PropiedadesRouteImport.update({
  id: '/propiedades',
  path: '/propiedades',
  getParentRoute: () => rootRouteImport,
} as any)
const CompraRoute = CompraRouteImport.update({
  id: '/compra',
  path: '/compra',
  getParentRoute: () => rootRouteImport,
} as any)
const AcercaRoute = AcercaRouteImport.update({
  id: '/acerca',
  path: '/acerca',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorRoute = VendedorRouteImport.update({
  id: '/_vendedor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedoresSignupRoute = VendedoresSignupRouteImport.update({
  id: '/vendedores/signup',
  path: '/vendedores/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedoresLoginRoute = VendedoresLoginRouteImport.update({
  id: '/vendedores/login',
  path: '/vendedores/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesIdRoute = PropiedadesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropiedadesRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const VendedorVendedoresDashboardRoute =
  VendedorVendedoresDashboardRouteImport.update({
    id: '/vendedores/dashboard',
    path: '/vendedores/dashboard',
    getParentRoute: () => VendedorRoute,
  } as any)
const VendedorVendedoresPropiedadesNuevaRoute =
  VendedorVendedoresPropiedadesNuevaRouteImport.update({
    id: '/vendedores/propiedades/nueva',
    path: '/vendedores/propiedades/nueva',
    getParentRoute: () => VendedorRoute,
  } as any)
const VendedorVendedoresPropiedadesIdEditarRoute =
  VendedorVendedoresPropiedadesIdEditarRouteImport.update({
    id: '/vendedores/propiedades/$id/editar',
    path: '/vendedores/propiedades/$id/editar',
    getParentRoute: () => VendedorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/compra': typeof CompraRoute
  '/propiedades': typeof PropiedadesRouteWithChildren
  '/publica': typeof PublicaRoute
  '/renta': typeof RentaRoute
  '/tasacion': typeof TasacionRoute
  '/admin': typeof AdminAdminRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/vendedores/login': typeof VendedoresLoginRoute
  '/vendedores/signup': typeof VendedoresSignupRoute
  '/vendedores/dashboard': typeof VendedorVendedoresDashboardRoute
  '/vendedores/propiedades/nueva': typeof VendedorVendedoresPropiedadesNuevaRoute
  '/vendedores/propiedades/$id/editar': typeof VendedorVendedoresPropiedadesIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/compra': typeof CompraRoute
  '/propiedades': typeof PropiedadesRouteWithChildren
  '/publica': typeof PublicaRoute
  '/renta': typeof RentaRoute
  '/tasacion': typeof TasacionRoute
  '/admin': typeof AdminAdminRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/vendedores/login': typeof VendedoresLoginRoute
  '/vendedores/signup': typeof VendedoresSignupRoute
  '/vendedores/dashboard': typeof VendedorVendedoresDashboardRoute
  '/vendedores/propiedades/nueva': typeof VendedorVendedoresPropiedadesNuevaRoute
  '/vendedores/propiedades/$id/editar': typeof VendedorVendedoresPropiedadesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_vendedor': typeof VendedorRouteWithChildren
  '/acerca': typeof AcercaRoute
  '/compra': typeof CompraRoute
  '/propiedades': typeof PropiedadesRouteWithChildren
  '/publica': typeof PublicaRoute
  '/renta': typeof RentaRoute
  '/tasacion': typeof TasacionRoute
  '/_admin/admin': typeof AdminAdminRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/vendedores/login': typeof VendedoresLoginRoute
  '/vendedores/signup': typeof VendedoresSignupRoute
  '/_vendedor/vendedores/dashboard': typeof VendedorVendedoresDashboardRoute
  '/_vendedor/vendedores/propiedades/nueva': typeof VendedorVendedoresPropiedadesNuevaRoute
  '/_vendedor/vendedores/propiedades/$id/editar': typeof VendedorVendedoresPropiedadesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acerca'
    | '/compra'
    | '/propiedades'
    | '/publica'
    | '/renta'
    | '/tasacion'
    | '/admin'
    | '/propiedades/$id'
    | '/vendedores/login'
    | '/vendedores/signup'
    | '/vendedores/dashboard'
    | '/vendedores/propiedades/nueva'
    | '/vendedores/propiedades/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acerca'
    | '/compra'
    | '/propiedades'
    | '/publica'
    | '/renta'
    | '/tasacion'
    | '/admin'
    | '/propiedades/$id'
    | '/vendedores/login'
    | '/vendedores/signup'
    | '/vendedores/dashboard'
    | '/vendedores/propiedades/nueva'
    | '/vendedores/propiedades/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_vendedor'
    | '/acerca'
    | '/compra'
    | '/propiedades'
    | '/publica'
    | '/renta'
    | '/tasacion'
    | '/_admin/admin'
    | '/propiedades/$id'
    | '/vendedores/login'
    | '/vendedores/signup'
    | '/_vendedor/vendedores/dashboard'
    | '/_vendedor/vendedores/propiedades/nueva'
    | '/_vendedor/vendedores/propiedades/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  VendedorRoute: typeof VendedorRouteWithChildren
  AcercaRoute: typeof AcercaRoute
  CompraRoute: typeof CompraRoute
  PropiedadesRoute: typeof PropiedadesRouteWithChildren
  PublicaRoute: typeof PublicaRoute
  RentaRoute: typeof RentaRoute
  TasacionRoute: typeof TasacionRoute
  VendedoresLoginRoute: typeof VendedoresLoginRoute
  VendedoresSignupRoute: typeof VendedoresSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasacion': {
      id: '/tasacion'
      path: '/tasacion'
      fullPath: '/tasacion'
      preLoaderRoute: typeof TasacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renta': {
      id: '/renta'
      path: '/renta'
      fullPath: '/renta'
      preLoaderRoute: typeof RentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publica': {
      id: '/publica'
      path: '/publica'
      fullPath: '/publica'
      preLoaderRoute: typeof PublicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades': {
      id: '/propiedades'
      path: '/propiedades'
      fullPath: '/propiedades'
      preLoaderRoute: typeof PropiedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compra': {
      id: '/compra'
      path: '/compra'
      fullPath: '/compra'
      preLoaderRoute: typeof CompraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acerca': {
      id: '/acerca'
      path: '/acerca'
      fullPath: '/acerca'
      preLoaderRoute: typeof AcercaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_vendedor': {
      id: '/_vendedor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof VendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedores/signup': {
      id: '/vendedores/signup'
      path: '/vendedores/signup'
      fullPath: '/vendedores/signup'
      preLoaderRoute: typeof VendedoresSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedores/login': {
      id: '/vendedores/login'
      path: '/vendedores/login'
      fullPath: '/vendedores/login'
      preLoaderRoute: typeof VendedoresLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades/$id': {
      id: '/propiedades/$id'
      path: '/$id'
      fullPath: '/propiedades/$id'
      preLoaderRoute: typeof PropiedadesIdRouteImport
      parentRoute: typeof PropiedadesRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_vendedor/vendedores/dashboard': {
      id: '/_vendedor/vendedores/dashboard'
      path: '/vendedores/dashboard'
      fullPath: '/vendedores/dashboard'
      preLoaderRoute: typeof VendedorVendedoresDashboardRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/_vendedor/vendedores/propiedades/nueva': {
      id: '/_vendedor/vendedores/propiedades/nueva'
      path: '/vendedores/propiedades/nueva'
      fullPath: '/vendedores/propiedades/nueva'
      preLoaderRoute: typeof VendedorVendedoresPropiedadesNuevaRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/_vendedor/vendedores/propiedades/$id/editar': {
      id: '/_vendedor/vendedores/propiedades/$id/editar'
      path: '/vendedores/propiedades/$id/editar'
      fullPath: '/vendedores/propiedades/$id/editar'
      preLoaderRoute: typeof VendedorVendedoresPropiedadesIdEditarRouteImport
      parentRoute: typeof VendedorRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface VendedorRouteChildren {
  VendedorVendedoresDashboardRoute: typeof VendedorVendedoresDashboardRoute
  VendedorVendedoresPropiedadesNuevaRoute: typeof VendedorVendedoresPropiedadesNuevaRoute
  VendedorVendedoresPropiedadesIdEditarRoute: typeof VendedorVendedoresPropiedadesIdEditarRoute
}

const VendedorRouteChildren: VendedorRouteChildren = {
  VendedorVendedoresDashboardRoute: VendedorVendedoresDashboardRoute,
  VendedorVendedoresPropiedadesNuevaRoute:
    VendedorVendedoresPropiedadesNuevaRoute,
  VendedorVendedoresPropiedadesIdEditarRoute:
    VendedorVendedoresPropiedadesIdEditarRoute,
}

const VendedorRouteWithChildren = VendedorRoute._addFileChildren(
  VendedorRouteChildren,
)

interface PropiedadesRouteChildren {
  PropiedadesIdRoute: typeof PropiedadesIdRoute
}

const PropiedadesRouteChildren: PropiedadesRouteChildren = {
  PropiedadesIdRoute: PropiedadesIdRoute,
}

const PropiedadesRouteWithChildren = PropiedadesRoute._addFileChildren(
  PropiedadesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  VendedorRoute: VendedorRouteWithChildren,
  AcercaRoute: AcercaRoute,
  CompraRoute: CompraRoute,
  PropiedadesRoute: PropiedadesRouteWithChildren,
  PublicaRoute: PublicaRoute,
  RentaRoute: RentaRoute,
  TasacionRoute: TasacionRoute,
  VendedoresLoginRoute: VendedoresLoginRoute,
  VendedoresSignupRoute: VendedoresSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
