/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasacionRouteImport } from './routes/tasacion'
import { Route as RentaRouteImport } from './routes/renta'
import { Route as PublicaRouteImport } from './routes/publica'
import { Route as CompraRouteImport } from './routes/compra'
import { Route as AcercaRouteImport } from './routes/acerca'
import { Route as VendedorRouteImport } from './routes/_vendedor'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropiedadesIndexRouteImport } from './routes/propiedades.index'
import { Route as VendedoresSignupRouteImport } from './routes/vendedores.signup'
import { Route as VendedoresLoginRouteImport } from './routes/vendedores.login'
import { Route as PropiedadesIdRouteImport } from './routes/propiedades.$id'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as VendedorVendedoresMetricasRouteImport } from './routes/_vendedor.vendedores.metricas'
import { Route as VendedorVendedoresDashboardRouteImport } from './routes/_vendedor.vendedores.dashboard'
import { Route as VendedorVendedoresCrmRouteImport } from './routes/_vendedor.vendedores.crm'
import { Route as VendedorVendedoresContenidoRouteImport } from './routes/_vendedor.vendedores.contenido'
import { Route as VendedorVendedoresComisionesRouteImport } from './routes/_vendedor.vendedores.comisiones'
import { Route as VendedorVendedoresAprobacionRouteImport } from './routes/_vendedor.vendedores.aprobacion'
import { Route as VendedorVendedoresAgendaRouteImport } from './routes/_vendedor.vendedores.agenda'
import { Route as VendedorVendedoresPropiedadesNuevaRouteImport } from './routes/_vendedor.vendedores.propiedades.nueva'
import { Route as VendedorVendedoresPropiedadesIdEditarRouteImport } from './routes/_vendedor.vendedores.propiedades.$id.editar'

const TasacionRoute = TasacionRouteImport.update({
  id: '/tasacion',
  path: '/tasacion',
  getParentRoute: () => rootRouteImport,
} as any)
const RentaRoute = RentaRouteImport.update({
  id: '/renta',
  path: '/renta',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicaRoute = PublicaRouteImport.update({
  id: '/publica',
  path: '/publica',
  getParentRoute: () => rootRouteImport,
} as any)
const CompraRoute = CompraRouteImport.update({
  id: '/compra',
  path: '/compra',
  getParentRoute: () => rootRouteImport,
} as any)
const AcercaRoute = AcercaRouteImport.update({
  id: '/acerca',
  path: '/acerca',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorRoute = VendedorRouteImport.update({
  id: '/_vendedor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesIndexRoute = PropiedadesIndexRouteImport.update({
  id: '/propiedades/',
  path: '/propiedades/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedoresSignupRoute = VendedoresSignupRouteImport.update({
  id: '/vendedores/signup',
  path: '/vendedores/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedoresLoginRoute = VendedoresLoginRouteImport.update({
  id: '/vendedores/login',
  path: '/vendedores/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesIdRoute = PropiedadesIdRouteImport.update({
  id: '/propiedades/$id',
  path: '/propiedades/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const VendedorVendedoresMetricasRoute =
  VendedorVendedoresMetricasRouteImport.update({
    id: '/vendedores/metricas',
    path: '/vendedores/metricas',
    getParentRoute: () => VendedorRoute,
  } as any)
const VendedorVendedoresDashboardRoute =
  VendedorVendedoresDashboardRouteImport.update({
    id: '/vendedores/dashboard',
    path: '/vendedores/dashboard',
    getParentRoute: () => VendedorRoute,
  } as any)
const VendedorVendedoresCrmRoute = VendedorVendedoresCrmRouteImport.update({
  id: '/vendedores/crm',
  path: '/vendedores/crm',
  getParentRoute: () => VendedorRoute,
} as any)
const VendedorVendedoresContenidoRoute =
  VendedorVendedoresContenidoRouteImport.update({
    id: '/vendedores/contenido',
    path: '/vendedores/contenido',
    getParentRoute: () => VendedorRoute,
  } as any)
const VendedorVendedoresComisionesRoute =
  VendedorVendedoresComisionesRouteImport.update({
    id: '/vendedores/comisiones',
    path: '/vendedores/comisiones',
    getParentRoute: () => VendedorRoute,
  } as any)
const VendedorVendedoresAprobacionRoute =
  VendedorVendedoresAprobacionRouteImport.update({
    id: '/vendedores/aprobacion',
    path: '/vendedores/aprobacion',
    getParentRoute: () => VendedorRoute,
  } as any)
const VendedorVendedoresAgendaRoute =
  VendedorVendedoresAgendaRouteImport.update({
    id: '/vendedores/agenda',
    path: '/vendedores/agenda',
    getParentRoute: () => VendedorRoute,
  } as any)
const VendedorVendedoresPropiedadesNuevaRoute =
  VendedorVendedoresPropiedadesNuevaRouteImport.update({
    id: '/vendedores/propiedades/nueva',
    path: '/vendedores/propiedades/nueva',
    getParentRoute: () => VendedorRoute,
  } as any)
const VendedorVendedoresPropiedadesIdEditarRoute =
  VendedorVendedoresPropiedadesIdEditarRouteImport.update({
    id: '/vendedores/propiedades/$id/editar',
    path: '/vendedores/propiedades/$id/editar',
    getParentRoute: () => VendedorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/compra': typeof CompraRoute
  '/publica': typeof PublicaRoute
  '/renta': typeof RentaRoute
  '/tasacion': typeof TasacionRoute
  '/admin': typeof AdminAdminRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/vendedores/login': typeof VendedoresLoginRoute
  '/vendedores/signup': typeof VendedoresSignupRoute
  '/propiedades/': typeof PropiedadesIndexRoute
  '/vendedores/agenda': typeof VendedorVendedoresAgendaRoute
  '/vendedores/aprobacion': typeof VendedorVendedoresAprobacionRoute
  '/vendedores/comisiones': typeof VendedorVendedoresComisionesRoute
  '/vendedores/contenido': typeof VendedorVendedoresContenidoRoute
  '/vendedores/crm': typeof VendedorVendedoresCrmRoute
  '/vendedores/dashboard': typeof VendedorVendedoresDashboardRoute
  '/vendedores/metricas': typeof VendedorVendedoresMetricasRoute
  '/vendedores/propiedades/nueva': typeof VendedorVendedoresPropiedadesNuevaRoute
  '/vendedores/propiedades/$id/editar': typeof VendedorVendedoresPropiedadesIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/compra': typeof CompraRoute
  '/publica': typeof PublicaRoute
  '/renta': typeof RentaRoute
  '/tasacion': typeof TasacionRoute
  '/admin': typeof AdminAdminRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/vendedores/login': typeof VendedoresLoginRoute
  '/vendedores/signup': typeof VendedoresSignupRoute
  '/propiedades': typeof PropiedadesIndexRoute
  '/vendedores/agenda': typeof VendedorVendedoresAgendaRoute
  '/vendedores/aprobacion': typeof VendedorVendedoresAprobacionRoute
  '/vendedores/comisiones': typeof VendedorVendedoresComisionesRoute
  '/vendedores/contenido': typeof VendedorVendedoresContenidoRoute
  '/vendedores/crm': typeof VendedorVendedoresCrmRoute
  '/vendedores/dashboard': typeof VendedorVendedoresDashboardRoute
  '/vendedores/metricas': typeof VendedorVendedoresMetricasRoute
  '/vendedores/propiedades/nueva': typeof VendedorVendedoresPropiedadesNuevaRoute
  '/vendedores/propiedades/$id/editar': typeof VendedorVendedoresPropiedadesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_vendedor': typeof VendedorRouteWithChildren
  '/acerca': typeof AcercaRoute
  '/compra': typeof CompraRoute
  '/publica': typeof PublicaRoute
  '/renta': typeof RentaRoute
  '/tasacion': typeof TasacionRoute
  '/_admin/admin': typeof AdminAdminRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/vendedores/login': typeof VendedoresLoginRoute
  '/vendedores/signup': typeof VendedoresSignupRoute
  '/propiedades/': typeof PropiedadesIndexRoute
  '/_vendedor/vendedores/agenda': typeof VendedorVendedoresAgendaRoute
  '/_vendedor/vendedores/aprobacion': typeof VendedorVendedoresAprobacionRoute
  '/_vendedor/vendedores/comisiones': typeof VendedorVendedoresComisionesRoute
  '/_vendedor/vendedores/contenido': typeof VendedorVendedoresContenidoRoute
  '/_vendedor/vendedores/crm': typeof VendedorVendedoresCrmRoute
  '/_vendedor/vendedores/dashboard': typeof VendedorVendedoresDashboardRoute
  '/_vendedor/vendedores/metricas': typeof VendedorVendedoresMetricasRoute
  '/_vendedor/vendedores/propiedades/nueva': typeof VendedorVendedoresPropiedadesNuevaRoute
  '/_vendedor/vendedores/propiedades/$id/editar': typeof VendedorVendedoresPropiedadesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acerca'
    | '/compra'
    | '/publica'
    | '/renta'
    | '/tasacion'
    | '/admin'
    | '/propiedades/$id'
    | '/vendedores/login'
    | '/vendedores/signup'
    | '/propiedades/'
    | '/vendedores/agenda'
    | '/vendedores/aprobacion'
    | '/vendedores/comisiones'
    | '/vendedores/contenido'
    | '/vendedores/crm'
    | '/vendedores/dashboard'
    | '/vendedores/metricas'
    | '/vendedores/propiedades/nueva'
    | '/vendedores/propiedades/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acerca'
    | '/compra'
    | '/publica'
    | '/renta'
    | '/tasacion'
    | '/admin'
    | '/propiedades/$id'
    | '/vendedores/login'
    | '/vendedores/signup'
    | '/propiedades'
    | '/vendedores/agenda'
    | '/vendedores/aprobacion'
    | '/vendedores/comisiones'
    | '/vendedores/contenido'
    | '/vendedores/crm'
    | '/vendedores/dashboard'
    | '/vendedores/metricas'
    | '/vendedores/propiedades/nueva'
    | '/vendedores/propiedades/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_vendedor'
    | '/acerca'
    | '/compra'
    | '/publica'
    | '/renta'
    | '/tasacion'
    | '/_admin/admin'
    | '/propiedades/$id'
    | '/vendedores/login'
    | '/vendedores/signup'
    | '/propiedades/'
    | '/_vendedor/vendedores/agenda'
    | '/_vendedor/vendedores/aprobacion'
    | '/_vendedor/vendedores/comisiones'
    | '/_vendedor/vendedores/contenido'
    | '/_vendedor/vendedores/crm'
    | '/_vendedor/vendedores/dashboard'
    | '/_vendedor/vendedores/metricas'
    | '/_vendedor/vendedores/propiedades/nueva'
    | '/_vendedor/vendedores/propiedades/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  VendedorRoute: typeof VendedorRouteWithChildren
  AcercaRoute: typeof AcercaRoute
  CompraRoute: typeof CompraRoute
  PublicaRoute: typeof PublicaRoute
  RentaRoute: typeof RentaRoute
  TasacionRoute: typeof TasacionRoute
  PropiedadesIdRoute: typeof PropiedadesIdRoute
  VendedoresLoginRoute: typeof VendedoresLoginRoute
  VendedoresSignupRoute: typeof VendedoresSignupRoute
  PropiedadesIndexRoute: typeof PropiedadesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasacion': {
      id: '/tasacion'
      path: '/tasacion'
      fullPath: '/tasacion'
      preLoaderRoute: typeof TasacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renta': {
      id: '/renta'
      path: '/renta'
      fullPath: '/renta'
      preLoaderRoute: typeof RentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publica': {
      id: '/publica'
      path: '/publica'
      fullPath: '/publica'
      preLoaderRoute: typeof PublicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compra': {
      id: '/compra'
      path: '/compra'
      fullPath: '/compra'
      preLoaderRoute: typeof CompraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acerca': {
      id: '/acerca'
      path: '/acerca'
      fullPath: '/acerca'
      preLoaderRoute: typeof AcercaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_vendedor': {
      id: '/_vendedor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof VendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades/': {
      id: '/propiedades/'
      path: '/propiedades'
      fullPath: '/propiedades/'
      preLoaderRoute: typeof PropiedadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedores/signup': {
      id: '/vendedores/signup'
      path: '/vendedores/signup'
      fullPath: '/vendedores/signup'
      preLoaderRoute: typeof VendedoresSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedores/login': {
      id: '/vendedores/login'
      path: '/vendedores/login'
      fullPath: '/vendedores/login'
      preLoaderRoute: typeof VendedoresLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades/$id': {
      id: '/propiedades/$id'
      path: '/propiedades/$id'
      fullPath: '/propiedades/$id'
      preLoaderRoute: typeof PropiedadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_vendedor/vendedores/metricas': {
      id: '/_vendedor/vendedores/metricas'
      path: '/vendedores/metricas'
      fullPath: '/vendedores/metricas'
      preLoaderRoute: typeof VendedorVendedoresMetricasRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/_vendedor/vendedores/dashboard': {
      id: '/_vendedor/vendedores/dashboard'
      path: '/vendedores/dashboard'
      fullPath: '/vendedores/dashboard'
      preLoaderRoute: typeof VendedorVendedoresDashboardRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/_vendedor/vendedores/crm': {
      id: '/_vendedor/vendedores/crm'
      path: '/vendedores/crm'
      fullPath: '/vendedores/crm'
      preLoaderRoute: typeof VendedorVendedoresCrmRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/_vendedor/vendedores/contenido': {
      id: '/_vendedor/vendedores/contenido'
      path: '/vendedores/contenido'
      fullPath: '/vendedores/contenido'
      preLoaderRoute: typeof VendedorVendedoresContenidoRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/_vendedor/vendedores/comisiones': {
      id: '/_vendedor/vendedores/comisiones'
      path: '/vendedores/comisiones'
      fullPath: '/vendedores/comisiones'
      preLoaderRoute: typeof VendedorVendedoresComisionesRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/_vendedor/vendedores/aprobacion': {
      id: '/_vendedor/vendedores/aprobacion'
      path: '/vendedores/aprobacion'
      fullPath: '/vendedores/aprobacion'
      preLoaderRoute: typeof VendedorVendedoresAprobacionRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/_vendedor/vendedores/agenda': {
      id: '/_vendedor/vendedores/agenda'
      path: '/vendedores/agenda'
      fullPath: '/vendedores/agenda'
      preLoaderRoute: typeof VendedorVendedoresAgendaRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/_vendedor/vendedores/propiedades/nueva': {
      id: '/_vendedor/vendedores/propiedades/nueva'
      path: '/vendedores/propiedades/nueva'
      fullPath: '/vendedores/propiedades/nueva'
      preLoaderRoute: typeof VendedorVendedoresPropiedadesNuevaRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/_vendedor/vendedores/propiedades/$id/editar': {
      id: '/_vendedor/vendedores/propiedades/$id/editar'
      path: '/vendedores/propiedades/$id/editar'
      fullPath: '/vendedores/propiedades/$id/editar'
      preLoaderRoute: typeof VendedorVendedoresPropiedadesIdEditarRouteImport
      parentRoute: typeof VendedorRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface VendedorRouteChildren {
  VendedorVendedoresAgendaRoute: typeof VendedorVendedoresAgendaRoute
  VendedorVendedoresAprobacionRoute: typeof VendedorVendedoresAprobacionRoute
  VendedorVendedoresComisionesRoute: typeof VendedorVendedoresComisionesRoute
  VendedorVendedoresContenidoRoute: typeof VendedorVendedoresContenidoRoute
  VendedorVendedoresCrmRoute: typeof VendedorVendedoresCrmRoute
  VendedorVendedoresDashboardRoute: typeof VendedorVendedoresDashboardRoute
  VendedorVendedoresMetricasRoute: typeof VendedorVendedoresMetricasRoute
  VendedorVendedoresPropiedadesNuevaRoute: typeof VendedorVendedoresPropiedadesNuevaRoute
  VendedorVendedoresPropiedadesIdEditarRoute: typeof VendedorVendedoresPropiedadesIdEditarRoute
}

const VendedorRouteChildren: VendedorRouteChildren = {
  VendedorVendedoresAgendaRoute: VendedorVendedoresAgendaRoute,
  VendedorVendedoresAprobacionRoute: VendedorVendedoresAprobacionRoute,
  VendedorVendedoresComisionesRoute: VendedorVendedoresComisionesRoute,
  VendedorVendedoresContenidoRoute: VendedorVendedoresContenidoRoute,
  VendedorVendedoresCrmRoute: VendedorVendedoresCrmRoute,
  VendedorVendedoresDashboardRoute: VendedorVendedoresDashboardRoute,
  VendedorVendedoresMetricasRoute: VendedorVendedoresMetricasRoute,
  VendedorVendedoresPropiedadesNuevaRoute:
    VendedorVendedoresPropiedadesNuevaRoute,
  VendedorVendedoresPropiedadesIdEditarRoute:
    VendedorVendedoresPropiedadesIdEditarRoute,
}

const VendedorRouteWithChildren = VendedorRoute._addFileChildren(
  VendedorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  VendedorRoute: VendedorRouteWithChildren,
  AcercaRoute: AcercaRoute,
  CompraRoute: CompraRoute,
  PublicaRoute: PublicaRoute,
  RentaRoute: RentaRoute,
  TasacionRoute: TasacionRoute,
  PropiedadesIdRoute: PropiedadesIdRoute,
  VendedoresLoginRoute: VendedoresLoginRoute,
  VendedoresSignupRoute: VendedoresSignupRoute,
  PropiedadesIndexRoute: PropiedadesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
