// This file is automatically generated. Safe ALTUM wrapper adjusted for production resilience.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const FALLBACK_SUPABASE_URL = 'https://example.supabase.co';
const FALLBACK_SUPABASE_KEY = 'public-anon-key';

function readSupabaseEnv() {
  const env = import.meta.env ?? {};
  const url =
    env.VITE_SUPABASE_URL ||
    env.SUPABASE_URL ||
    (typeof process !== 'undefined' ? process.env.SUPABASE_URL : undefined);

  const key =
    env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    env.VITE_SUPABASE_ANON_KEY ||
    env.SUPABASE_PUBLISHABLE_KEY ||
    env.SUPABASE_ANON_KEY ||
    (typeof process !== 'undefined' ? process.env.SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_ANON_KEY : undefined);

  return { url, key };
}

export function isSupabaseConfigured() {
  const { url, key } = readSupabaseEnv();
  return Boolean(url && key);
}

function createSupabaseClient() {
  const { url, key } = readSupabaseEnv();

  if (!url || !key) {
    console.warn(
      '[Supabase] Missing Supabase environment variables. Public pages will load in limited mode. Configure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY / VITE_SUPABASE_ANON_KEY.',
    );
  }

  return createClient<Database>(url || FALLBACK_SUPABASE_URL, key || FALLBACK_SUPABASE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
